---
- import_tasks: install.yml
  tags:
    - frr
    - frr-install
    - never
- import_tasks: configure/ufw.yml
  tags:
    - frr
    - frr-configure-ufw
    - never
- import_tasks: configure/base.yml
  tags:
    - frr
    - frr-configure-base
    - never
